spring.application.name=Commerce
spring.jpa.show-sql=true
spring.profiles.active=dev

# Cookie security settings (override in profile-specific properties)
cookie.secure=true
cookie.sameSite=Strict


# Email Configuration (Gmail SMTP)
